# Generated by Django 3.2.5 on 2022-03-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('sex', models.CharField(choices=[('1', '男'), ('2', '女')], default='男', max_length=20)),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.EmailField(max_length=50, verbose_name='电子邮箱')),
                ('phone', models.IntegerField(verbose_name='电话')),
                ('lastlogintime', models.DateTimeField(verbose_name='上次登录时间')),
                ('registertime', models.DateTimeField(auto_now=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='', verbose_name='图片路径')),
                ('name', models.CharField(max_length=50, verbose_name='图片名')),
                ('uploadtime', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
                ('downloadtimes', models.IntegerField(verbose_name='下载次数')),
                ('liker', models.ManyToManyField(related_name='liker', to='photo.UserInfo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='photo.userinfo', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '图片表',
                'verbose_name_plural': '图片表',
            },
        ),
    ]
