# Generated by Django 3.2.5 on 2022-03-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='lastlogintime',
            field=models.DateTimeField(blank=True, verbose_name='上次登录时间'),
        ),
    ]
