# Generated by Django 3.2.12 on 2022-03-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_userinfo_lastlogintime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(unique=True, verbose_name='电话'),
        ),
    ]
