# Generated by Django 3.2.12 on 2022-03-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_rename_registercode_userinfo_phonecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='likenum',
            field=models.IntegerField(default=0, verbose_name='赞'),
        ),
    ]
