# Generated by Django 3.2.12 on 2022-03-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_photo_likenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
