# Generated by Django 3.2.12 on 2022-03-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_photo_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='hot',
            field=models.FloatField(default=0, verbose_name='热度'),
        ),
    ]
