# Generated by Django 3.2.12 on 2022-03-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_auto_20220322_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
    ]
