# Generated by Django 3.2.12 on 2022-03-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_auto_20220322_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(unique=True, verbose_name='电话'),
        ),
    ]
