# Generated by Django 3.2.12 on 2022-03-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0016_photo_thumbimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploadtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
