# Generated by Django 3.2.12 on 2022-03-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0017_alter_photo_uploadtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='sex',
        ),
    ]
